// Define TypeScript interfaces
export interface Emoji {
    char: string;
    name: string;
}

export interface EmojiCategory {
    name: string;
    emojis: Emoji[];
}

export const EmojiCategories: EmojiCategory[] = [
    {
        name: 'Smileys & Emotion',
        emojis: [
            { char: '😀', name: 'grinning face' },
            { char: '😃', name: 'grinning face with big eyes' },
            { char: '😄', name: 'grinning face with smiling eyes' },
            { char: '😁', name: 'beaming face with smiling eyes' },
            { char: '😆', name: 'grinning squinting face' },
            { char: '😅', name: 'grinning face with sweat' },
            { char: '😂', name: 'face with tears of joy' },
            { char: '🤣', name: 'rolling on the floor laughing' },
            { char: '😊', name: 'smiling face with smiling eyes' },
            { char: '😇', name: 'smiling face with halo' },
            { char: '🙂', name: 'slightly smiling face' },
            { char: '🙃', name: 'upside-down face' },
            { char: '😉', name: 'winking face' },
            { char: '😌', name: 'relieved face' },
            { char: '😍', name: 'smiling face with heart-eyes' },
            { char: '🥰', name: 'smiling face with hearts' },
            { char: '😘', name: 'face blowing a kiss' },
            { char: '😗', name: 'kissing face' },
            { char: '😙', name: 'kissing face with smiling eyes' },
            { char: '😚', name: 'kissing face with closed eyes' },
            { char: '😋', name: 'face savoring food' },
            { char: '😛', name: 'face with tongue' },
            { char: '😜', name: 'winking face with tongue' },
            { char: '😝', name: 'squinting face with tongue' },
            { char: '🤑', name: 'money-mouth face' },
            { char: '🤗', name: 'hugging face' },
            { char: '🤭', name: 'face with hand over mouth' },
            { char: '🤫', name: 'shushing face' },
            { char: '🤔', name: 'thinking face' },
            { char: '🤐', name: 'zipper-mouth face' },
            { char: '🤨', name: 'face with raised eyebrow' },
            { char: '😐', name: 'neutral face' },
            { char: '😑', name: 'expressionless face' },
            { char: '😶', name: 'face without mouth' },
            { char: '😏', name: 'smirking face' },
            { char: '😒', name: 'unamused face' },
            { char: '🙄', name: 'face with rolling eyes' },
            { char: '😬', name: 'grimacing face' },
            { char: '🤥', name: 'lying face' },
            { char: '😌', name: 'relieved face' },
            { char: '😔', name: 'pensive face' },
            { char: '😪', name: 'sleepy face' },
            { char: '🤤', name: 'drooling face' },
            { char: '😴', name: 'sleeping face' },
            { char: '😷', name: 'face with medical mask' },
            { char: '🤒', name: 'face with thermometer' },
            { char: '🤕', name: 'face with head-bandage' },
            { char: '🤢', name: 'nauseated face' },
            { char: '🤮', name: 'face vomiting' },
            { char: '🤧', name: 'sneezing face' }
        ]
    },
    {
        name: 'Face Negative',
        emojis: [
            { char: '😕', name: 'confused face' },
            { char: '😟', name: 'worried face' },
            { char: '🙁', name: 'slightly frowning face' },
            { char: '☹️', name: 'frowning face' },
            { char: '😮', name: 'face with open mouth' },
            { char: '😯', name: 'hushed face' },
            { char: '😲', name: 'astonished face' },
            { char: '😳', name: 'flushed face' },
            { char: '🥺', name: 'pleading face' },
            { char: '😦', name: 'frowning face with open mouth' },
            { char: '😧', name: 'anguished face' },
            { char: '😨', name: 'fearful face' },
            { char: '😰', name: 'anxious face with sweat' },
            { char: '😥', name: 'sad but relieved face' },
            { char: '😢', name: 'crying face' },
            { char: '😭', name: 'loudly crying face' },
            { char: '😱', name: 'face screaming in fear' },
            { char: '😖', name: 'confounded face' },
            { char: '😣', name: 'persevering face' },
            { char: '😞', name: 'disappointed face' },
            { char: '😓', name: 'downcast face with sweat' },
            { char: '😩', name: 'weary face' },
            { char: '😫', name: 'tired face' },
            { char: '🥱', name: 'yawning face' }
        ]
    },
    {
        name: 'Face Costume',
        emojis: [
            { char: '😈', name: 'smiling face with horns' },
            { char: '👿', name: 'angry face with horns' },
            { char: '👹', name: 'ogre' },
            { char: '👺', name: 'goblin' },
            { char: '💀', name: 'skull' },
            { char: '☠️', name: 'skull and crossbones' },
            { char: '👻', name: 'ghost' },
            { char: '👽', name: 'alien' },
            { char: '👾', name: 'alien monster' },
            { char: '🤖', name: 'robot' },
            { char: '🎃', name: 'jack-o-lantern' },
            { char: '😺', name: 'grinning cat' },
            { char: '😸', name: 'grinning cat with smiling eyes' },
            { char: '😹', name: 'cat with tears of joy' },
            { char: '😻', name: 'smiling cat with heart-eyes' },
            { char: '😼', name: 'cat with wry smile' },
            { char: '😽', name: 'kissing cat' },
            { char: '🙀', name: 'weary cat' },
            { char: '😿', name: 'crying cat' },
            { char: '😾', name: 'pouting cat' }
        ]
    },
    {
        name: 'People & Body',
        emojis: [
            { char: '👋', name: 'waving hand' },
            { char: '🤚', name: 'raised back of hand' },
            { char: '🖐️', name: 'hand with fingers splayed' },
            { char: '✋', name: 'raised hand' },
            { char: '🖖', name: 'vulcan salute' },
            { char: '👌', name: 'OK hand' },
            { char: '🤌', name: 'pinched fingers' },
            { char: '🤏', name: 'pinching hand' },
            { char: '✌️', name: 'victory hand' },
            { char: '🤞', name: 'crossed fingers' },
            { char: '🤟', name: 'love-you gesture' },
            { char: '🤘', name: 'sign of the horns' },
            { char: '🤙', name: 'call me hand' },
            { char: '👈', name: 'backhand index pointing left' },
            { char: '👉', name: 'backhand index pointing right' },
            { char: '👆', name: 'backhand index pointing up' },
            { char: '🖕', name: 'middle finger' },
            { char: '👇', name: 'backhand index pointing down' },
            { char: '☝️', name: 'index pointing up' },
            { char: '👍', name: 'thumbs up' },
            { char: '👎', name: 'thumbs down' },
            { char: '✊', name: 'raised fist' },
            { char: '👊', name: 'oncoming fist' },
            { char: '🤛', name: 'left-facing fist' },
            { char: '🤜', name: 'right-facing fist' },
            { char: '👏', name: 'clapping hands' },
            { char: '🙌', name: 'raising hands' },
            { char: '👐', name: 'open hands' },
            { char: '🤲', name: 'palms up together' },
            { char: '🤝', name: 'handshake' },
            { char: '🙏', name: 'folded hands' },
            { char: '✍️', name: 'writing hand' },
            { char: '💅', name: 'nail polish' },
            { char: '🤳', name: 'selfie' },
            { char: '💪', name: 'flexed biceps' },
            { char: '🦾', name: 'mechanical arm' },
            { char: '🦿', name: 'mechanical leg' },
            { char: '🦵', name: 'leg' },
            { char: '🦶', name: 'foot' },
            { char: '👂', name: 'ear' },
            { char: '🦻', name: 'ear with hearing aid' }
        ]
    },
    {
        name: 'Body Parts',
        emojis: [
            { char: '👃', name: 'nose' },
            { char: '🧠', name: 'brain' },
            { char: '🫀', name: 'anatomical heart' },
            { char: '🫁', name: 'lungs' },
            { char: '🦷', name: 'tooth' },
            { char: '🦴', name: 'bone' },
            { char: '👀', name: 'eyes' },
            { char: '👁️', name: 'eye' },
            { char: '👅', name: 'tongue' },
            { char: '👄', name: 'mouth' }
        ]
    },
    {
        name: 'Person',
        emojis: [
            { char: '👶', name: 'baby' },
            { char: '🧒', name: 'child' },
            { char: '👦', name: 'boy' },
            { char: '👧', name: 'girl' },
            { char: '🧑', name: 'person' },
            { char: '👱', name: 'person with blond hair' },
            { char: '👨', name: 'man' },
            { char: '🧔', name: 'person with beard' },
            { char: '👨‍🦰', name: 'man with red hair' },
            { char: '👨‍🦱', name: 'man with curly hair' },
            { char: '👨‍🦳', name: 'man with white hair' },
            { char: '👨‍🦲', name: 'man with bald head' },
            { char: '👩', name: 'woman' },
            { char: '👩‍🦰', name: 'woman with red hair' },
            { char: '👩‍🦱', name: 'woman with curly hair' },
            { char: '👩‍🦳', name: 'woman with white hair' },
            { char: '👩‍🦲', name: 'woman with bald head' },
            { char: '👴', name: 'old man' },
            { char: '👵', name: 'old woman' },
            { char: '🧓', name: 'older person' }
        ]
    },
    {
        name: 'Person Gesture',
        emojis: [
            { char: '🙍', name: 'person frowning' },
            { char: '🙎', name: 'person pouting' },
            { char: '🙅', name: 'person gesturing NO' },
            { char: '🙆', name: 'person gesturing OK' },
            { char: '💁', name: 'person tipping hand' },
            { char: '🙋', name: 'person raising hand' },
            { char: '🧏', name: 'deaf person' },
            { char: '🙇', name: 'person bowing' },
            { char: '🤦', name: 'person facepalming' },
            { char: '🤷', name: 'person shrugging' }
        ]
    },
    {
        name: 'Animals & Nature',
        emojis: [
            { char: '🐶', name: 'dog face' },
            { char: '🐕', name: 'dog' },
            { char: '🦮', name: 'guide dog' },
            { char: '🐕‍🦺', name: 'service dog' },
            { char: '🐩', name: 'poodle' },
            { char: '🐺', name: 'wolf' },
            { char: '🦊', name: 'fox' },
            { char: '🦝', name: 'raccoon' },
            { char: '🐱', name: 'cat face' },
            { char: '🐈', name: 'cat' },
            { char: '🐈‍⬛', name: 'black cat' },
            { char: '🦁', name: 'lion' },
            { char: '🐯', name: 'tiger face' },
            { char: '🐅', name: 'tiger' },
            { char: '🐆', name: 'leopard' },
            { char: '🐴', name: 'horse face' },
            { char: '🐎', name: 'horse' },
            { char: '🦄', name: 'unicorn' },
            { char: '🦓', name: 'zebra' },
            { char: '🦌', name: 'deer' },
            { char: '🐮', name: 'cow face' },
            { char: '🐂', name: 'ox' },
            { char: '🐃', name: 'water buffalo' },
            { char: '🐄', name: 'cow' },
            { char: '🐷', name: 'pig face' },
            { char: '🐖', name: 'pig' },
            { char: '🐗', name: 'boar' },
            { char: '🐽', name: 'pig nose' },
            { char: '🐏', name: 'ram' },
            { char: '🐑', name: 'ewe' }
        ]
    },
    {
        name: 'More Animals',
        emojis: [
            { char: '🐐', name: 'goat' },
            { char: '🐪', name: 'camel' },
            { char: '🐫', name: 'two-hump camel' },
            { char: '🦙', name: 'llama' },
            { char: '🦒', name: 'giraffe' },
            { char: '🐘', name: 'elephant' },
            { char: '🦣', name: 'mammoth' },
            { char: '🦏', name: 'rhinoceros' },
            { char: '🦛', name: 'hippopotamus' },
            { char: '🐭', name: 'mouse face' },
            { char: '🐁', name: 'mouse' },
            { char: '🐀', name: 'rat' },
            { char: '🐹', name: 'hamster' },
            { char: '🐰', name: 'rabbit face' },
            { char: '🐇', name: 'rabbit' },
            { char: '🐿️', name: 'chipmunk' },
            { char: '🦫', name: 'beaver' },
            { char: '🦔', name: 'hedgehog' },
            { char: '🦇', name: 'bat' },
            { char: '🐻', name: 'bear' },
            { char: '🐻‍❄️', name: 'polar bear' },
            { char: '🐨', name: 'koala' },
            { char: '🐼', name: 'panda' },
            { char: '🦘', name: 'kangaroo' },
            { char: '🦡', name: 'badger' }
        ]
    },
    {
        name: 'Birds',
        emojis: [
            { char: '🦃', name: 'turkey' },
            { char: '🐔', name: 'chicken' },
            { char: '🐓', name: 'rooster' },
            { char: '🐣', name: 'hatching chick' },
            { char: '🐤', name: 'baby chick' },
            { char: '🐥', name: 'front-facing baby chick' },
            { char: '🐦', name: 'bird' },
            { char: '🐧', name: 'penguin' },
            { char: '🕊️', name: 'dove' },
            { char: '🦅', name: 'eagle' },
            { char: '🦆', name: 'duck' },
            { char: '🦢', name: 'swan' },
            { char: '🦉', name: 'owl' },
            { char: '🦤', name: 'dodo' },
            { char: '🪶', name: 'feather' }
        ]
    },
    {
        name: 'Reptiles & Amphibians',
        emojis: [
            { char: '🐸', name: 'frog' },
            { char: '🐊', name: 'crocodile' },
            { char: '🐢', name: 'turtle' },
            { char: '🦎', name: 'lizard' },
            { char: '🐍', name: 'snake' },
            { char: '🐲', name: 'dragon face' },
            { char: '🐉', name: 'dragon' }
        ]
    },
    {
        name: 'Marine Animals',
        emojis: [
            { char: '🐳', name: 'spouting whale' },
            { char: '🐋', name: 'whale' },
            { char: '🐬', name: 'dolphin' },
            { char: '🦭', name: 'seal' },
            { char: '🐟', name: 'fish' },
            { char: '🐠', name: 'tropical fish' },
            { char: '🐡', name: 'blowfish' },
            { char: '🦈', name: 'shark' },
            { char: '🐙', name: 'octopus' },
            { char: '🐚', name: 'spiral shell' },
            { char: '🪸', name: 'coral' }
        ]
    },
    {
        name: 'Insects',
        emojis: [
            { char: '🐌', name: 'snail' },
            { char: '🦋', name: 'butterfly' },
            { char: '🐛', name: 'bug' },
            { char: '🐜', name: 'ant' },
            { char: '🐝', name: 'honeybee' },
            { char: '🪲', name: 'beetle' },
            { char: '🐞', name: 'lady beetle' },
            { char: '🦗', name: 'cricket' },
            { char: '🪳', name: 'cockroach' },
            { char: '🕷️', name: 'spider' },
            { char: '🕸️', name: 'spider web' },
            { char: '🦂', name: 'scorpion' },
            { char: '🦟', name: 'mosquito' },
            { char: '🦠', name: 'microbe' }
        ]
    },
    {
        name: 'Plants & Flowers',
        emojis: [
            { char: '💐', name: 'bouquet' },
            { char: '🌸', name: 'cherry blossom' },
            { char: '💮', name: 'white flower' },
            { char: '🏵️', name: 'rosette' },
            { char: '🌹', name: 'rose' },
            { char: '🥀', name: 'wilted flower' },
            { char: '🌺', name: 'hibiscus' },
            { char: '🌻', name: 'sunflower' },
            { char: '🌼', name: 'blossom' },
            { char: '🌷', name: 'tulip' },
            { char: '🌱', name: 'seedling' },
            { char: '🪴', name: 'potted plant' },
            { char: '🌲', name: 'evergreen tree' },
            { char: '🌳', name: 'deciduous tree' },
            { char: '🌴', name: 'palm tree' },
            { char: '🌵', name: 'cactus' },
            { char: '🌾', name: 'sheaf of rice' },
            { char: '🌿', name: 'herb' },
            { char: '☘️', name: 'shamrock' },
            { char: '🍀', name: 'four leaf clover' },
            { char: '🍁', name: 'maple leaf' },
            { char: '🍂', name: 'fallen leaf' },
            { char: '🍃', name: 'leaf fluttering in wind' }
        ]
    },
    {
        name: 'Food & Drink',
        emojis: [
            { char: '🍇', name: 'grapes' },
            { char: '🍈', name: 'melon' },
            { char: '🍉', name: 'watermelon' },
            { char: '🍊', name: 'tangerine' },
            { char: '🍋', name: 'lemon' },
            { char: '🍌', name: 'banana' },
            { char: '🍍', name: 'pineapple' },
            { char: '🥭', name: 'mango' },
            { char: '🍎', name: 'red apple' },
            { char: '🍏', name: 'green apple' },
            { char: '🍐', name: 'pear' },
            { char: '🍑', name: 'peach' },
            { char: '🍒', name: 'cherries' },
            { char: '🍓', name: 'strawberry' },
            { char: '🫐', name: 'blueberries' },
            { char: '🥝', name: 'kiwi fruit' },
            { char: '🍅', name: 'tomato' },
            { char: '🫒', name: 'olive' },
            { char: '🥥', name: 'coconut' },
            { char: '🥑', name: 'avocado' }
        ]
    },
    {
        name: 'Prepared Food',
        emojis: [
            { char: '🍞', name: 'bread' },
            { char: '🥐', name: 'croissant' },
            { char: '🥖', name: 'baguette bread' },
            { char: '🥨', name: 'pretzel' },
            { char: '🥯', name: 'bagel' },
            { char: '🥞', name: 'pancakes' },
            { char: '🧇', name: 'waffle' },
            { char: '🧀', name: 'cheese wedge' },
            { char: '🍖', name: 'meat on bone' },
            { char: '🍗', name: 'poultry leg' },
            { char: '🥩', name: 'cut of meat' },
            { char: '🥓', name: 'bacon' },
            { char: '🍔', name: 'hamburger' },
            { char: '🍟', name: 'french fries' },
            { char: '🍕', name: 'pizza' },
            { char: '🌭', name: 'hot dog' },
            { char: '🥪', name: 'sandwich' },
            { char: '🌮', name: 'taco' },
            { char: '🌯', name: 'burrito' },
            { char: '🫔', name: 'tamale' }
        ]
    },
    {
        name: 'Drinks',
        emojis: [
            { char: '🥤', name: 'cup with straw' },
            { char: '🧋', name: 'bubble tea' },
            { char: '🧃', name: 'beverage box' },
            { char: '🧉', name: 'mate' },
            { char: '🧊', name: 'ice' },
            { char: '🍶', name: 'sake' },
            { char: '🍾', name: 'bottle with popping cork' },
            { char: '🍷', name: 'wine glass' },
            { char: '🍸', name: 'cocktail glass' },
            { char: '🍹', name: 'tropical drink' },
            { char: '🍺', name: 'beer mug' },
            { char: '🍻', name: 'clinking beer mugs' },
            { char: '🥂', name: 'clinking glasses' },
            { char: '🥃', name: 'tumbler glass' },
            { char: '☕', name: 'hot beverage' },
            { char: '🫖', name: 'teapot' },
            { char: '🍵', name: 'teacup without handle' }
        ]
    },
    {
        name: 'Travel & Places',
        emojis: [
            { char: '🚗', name: 'automobile' },
            { char: '🚕', name: 'taxi' },
            { char: '🚙', name: 'sport utility vehicle' },
            { char: '🚌', name: 'bus' },
            { char: '🚎', name: 'trolleybus' },
            { char: '🏎️', name: 'racing car' },
            { char: '🚓', name: 'police car' },
            { char: '🚑', name: 'ambulance' },
            { char: '🚒', name: 'fire engine' },
            { char: '🚐', name: 'minibus' },
            { char: '🚚', name: 'delivery truck' },
            { char: '🚛', name: 'articulated lorry' },
            { char: '🚜', name: 'tractor' },
            { char: '🏍️', name: 'motorcycle' },
            { char: '🛵', name: 'motor scooter' },
            { char: '🚲', name: 'bicycle' },
            { char: '🚂', name: 'locomotive' },
            { char: '🚆', name: 'train' },
            { char: '🚊', name: 'tram' },
            { char: '🚉', name: 'station' }
        ]
    },
    {
        name: 'Air & Water Transport',
        emojis: [
            { char: '✈️', name: 'airplane' },
            { char: '🛩️', name: 'small airplane' },
            { char: '🚁', name: 'helicopter' },
            { char: '🚀', name: 'rocket' },
            { char: '🛸', name: 'flying saucer' },
            { char: '⛵', name: 'sailboat' },
            { char: '🚢', name: 'ship' },
            { char: '🛥️', name: 'motor boat' },
            { char: '🛳️', name: 'passenger ship' },
            { char: '⚓', name: 'anchor' }
        ]
    },
    {
        name: 'Time',
        emojis: [
            { char: '⌛', name: 'hourglass done' },
            { char: '⏳', name: 'hourglass not done' },
            { char: '⌚', name: 'watch' },
            { char: '⏰', name: 'alarm clock' },
            { char: '⏱️', name: 'stopwatch' },
            { char: '⏲️', name: 'timer clock' },
            { char: '🕰️', name: 'mantelpiece clock' },
            { char: '🕛', name: "twelve o'clock" },
            { char: '🕧', name: 'twelve-thirty' },
            { char: '🕐', name: "one o'clock" }
        ]
    },
    {
        name: 'Sky & Weather',
        emojis: [
            { char: '☀️', name: 'sun' },
            { char: '🌝', name: 'full moon face' },
            { char: '🌞', name: 'sun with face' },
            { char: '⭐', name: 'star' },
            { char: '🌟', name: 'glowing star' },
            { char: '🌠', name: 'shooting star' },
            { char: '☁️', name: 'cloud' },
            { char: '⛅', name: 'cloudy' }
        ]
    }
];