import { EmojiCategory } from "@/types/emoji";

export const emojiCategories: EmojiCategory[] = [
    {
        name: 'emotion',
        emojis: [
            { char: '😀', names: {} },
            //{ char: '😃', names: {} },
            { char: '😄', names: {} },
            { char: '😁', names: {} },
            { char: '😆', names: {} },
            { char: '😅', names: {} },
            { char: '😂', names: {} },
            { char: '🤣', names: {} },
            { char: '😊', names: {} },
            { char: '😇', names: {} },
            { char: '🙂', names: {} },
            { char: '🙃', names: {} },
            { char: '😉', names: {} },
            { char: '😌', names: {} },
            { char: '😍', names: {} },
            { char: '🥰', names: {} },
            { char: '😘', names: {} },
            { char: '😗', names: {} },
            { char: '😙', names: {} },
            { char: '😚', names: {} },
            { char: '😋', names: {} },
            { char: '😛', names: {} },
            { char: '😜', names: {} },
            { char: '😝', names: {} },
            { char: '🤑', names: {} },
            { char: '🤗', names: {} },
            { char: '🤭', names: {} },
            { char: '🤫', names: {} },
            { char: '🤔', names: {} },
            { char: '🤐', names: {} },
            { char: '🤨', names: {} },
            { char: '😐', names: {} },
            { char: '😑', names: {} },
            { char: '😶', names: {} },
            { char: '😏', names: {} },
            { char: '😒', names: {} },
            { char: '🙄', names: {} },
            { char: '😬', names: {} },
            { char: '🤥', names: {} },
            //{ char: '😌', names: {} },
            { char: '😔', names: {} },
            //{ char: '😪', names: {} },
            { char: '🤤', names: {} },
            { char: '😴', names: {} },
            { char: '😷', names: {} },
            { char: '🤒', names: {} },
            { char: '🤕', names: {} },
            { char: '🤢', names: {} },
            { char: '🤮', names: {} },
            { char: '🤧', names: {} },
        ]
    },
    {
        name: 'face_negative',
        emojis: [
            { char: '😕', names: {} },
            { char: '😟', names: {} },
            { char: '🙁', names: {} },
            { char: '☹️', names: {} },
            { char: '😮', names: {} },
            { char: '😯', names: {} },
            { char: '😲', names: {} },
            { char: '😳', names: {} },
            { char: '🥺', names: {} },
            { char: '😦', names: {} },
            { char: '😧', names: {} },
            { char: '😨', names: {} },
            { char: '😰', names: {} },
            { char: '😥', names: {} },
            { char: '😢', names: {} },
            { char: '😭', names: {} },
            { char: '😱', names: {} },
            { char: '😖', names: {} },
            { char: '😣', names: {} },
            { char: '😞', names: {} },
            { char: '😓', names: {} },
            { char: '😩', names: {} },
            { char: '😫', names: {} },
            { char: '🥱', names: {} },
        ]
    },
    {
        name: 'costume',
        emojis: [
            { char: '😈', names: {} },
            { char: '👿', names: {} },
            { char: '👹', names: {} },
            { char: '👺', names: {} },
            { char: '💀', names: {} },
            { char: '☠️', names: {} },
            { char: '👻', names: {} },
            { char: '👽', names: {} },
            { char: '👾', names: {} },
            { char: '🤖', names: {} },
            { char: '🎃', names: {} },
            { char: '😺', names: {} },
            { char: '😸', names: {} },
            { char: '😹', names: {} },
            { char: '😻', names: {} },
            { char: '😼', names: {} },
            { char: '😽', names: {} },
            { char: '🙀', names: {} },
            { char: '😿', names: {} },
            { char: '😾', names: {} },
        ]
    },
    {
        name: 'people',
        emojis: [
            { char: '👋', names: {} },
            { char: '🤚', names: {} },
            { char: '🖐️', names: {} },
            { char: '✋', names: {} },
            { char: '🖖', names: {} },
            { char: '👌', names: {} },
            { char: '🤌', names: {} },
            { char: '🤏', names: {} },
            { char: '✌️', names: {} },
            { char: '🤞', names: {} },
            { char: '🤟', names: {} },
            { char: '🤘', names: {} },
            { char: '🤙', names: {} },
            { char: '👈', names: {} },
            { char: '👉', names: {} },
            { char: '👆', names: {} },
            { char: '🖕', names: {} },
            { char: '👇', names: {} },
            { char: '☝️', names: {} },
            { char: '👍', names: {} },
            { char: '👎', names: {} },
            { char: '✊', names: {} },
            { char: '👊', names: {} },
            { char: '🤛', names: {} },
            { char: '🤜', names: {} },
            { char: '👏', names: {} },
            { char: '🙌', names: {} },
            { char: '👐', names: {} },
            { char: '🤲', names: {} },
            { char: '🤝', names: {} },
            { char: '🙏', names: {} },
            { char: '✍️', names: {} },
            { char: '💅', names: {} },
            { char: '🤳', names: {} },
            { char: '💪', names: {} },
            { char: '🦾', names: {} },
            { char: '🦿', names: {} },
            { char: '🦵', names: {} },
            { char: '🦶', names: {} },
            { char: '👂', names: {} },
            { char: '🦻', names: {} },
        ]
    },
    {
        name: 'body',
        emojis: [
            { char: '👃', names: {} },
            { char: '🧠', names: {} },
            { char: '🫀', names: {} },
            { char: '🫁', names: {} },
            { char: '🦷', names: {} },
            { char: '🦴', names: {} },
            { char: '👀', names: {} },
            { char: '👁️', names: {} },
            { char: '👅', names: {} },
            { char: '👄', names: {} },
        ]
    },
    {
        name: 'person',
        emojis: [
            { char: '👶', names: {} },
            { char: '🧒', names: {} },
            { char: '👦', names: {} },
            { char: '👧', names: {} },
            { char: '🧑', names: {} },
            { char: '👱', names: {} },
            { char: '👨', names: {} },
            { char: '🧔', names: {} },
            { char: '👨‍🦰', names: {} },
            { char: '👨‍🦱', names: {} },
            { char: '👨‍🦳', names: {} },
            { char: '👨‍🦲', names: {} },
            { char: '👩', names: {} },
            { char: '👩‍🦰', names: {} },
            { char: '👩‍🦱', names: {} },
            { char: '👩‍🦳', names: {} },
            { char: '👩‍🦲', names: {} },
            { char: '👴', names: {} },
            { char: '👵', names: {} },
            { char: '🧓', names: {} },
        ]
    },
    {
        name: 'gesture',
        emojis: [
            { char: '🙍', names: {} },
            { char: '🙎', names: {} },
            { char: '🙅', names: {} },
            { char: '🙆', names: {} },
            { char: '💁', names: {} },
            { char: '🙋', names: {} },
            { char: '🧏', names: {} },
            { char: '🙇', names: {} },
            { char: '🤦', names: {} },
            { char: '🤷', names: {} },
        ]
    },
    {
        name: 'nature',
        emojis: [
            { char: '🐶', names: {} },
            { char: '🐕', names: {} },
            { char: '🦮', names: {} },
            { char: '🐕‍🦺', names: {} },
            { char: '🐩', names: {} },
            { char: '🐺', names: {} },
            { char: '🦊', names: {} },
            { char: '🦝', names: {} },
            { char: '🐱', names: {} },
            { char: '🐈', names: {} },
            { char: '🐈‍⬛', names: {} },
            { char: '🦁', names: {} },
            { char: '🐯', names: {} },
            { char: '🐅', names: {} },
            { char: '🐆', names: {} },
            { char: '🐴', names: {} },
            { char: '🐎', names: {} },
            { char: '🦄', names: {} },
            { char: '🦓', names: {} },
            { char: '🦌', names: {} },
            { char: '🐮', names: {} },
            { char: '🐂', names: {} },
            { char: '🐃', names: {} },
            { char: '🐄', names: {} },
            { char: '🐷', names: {} },
            { char: '🐖', names: {} },
            { char: '🐗', names: {} },
            { char: '🐽', names: {} },
            { char: '🐏', names: {} },
            { char: '🐑', names: {} },
        ]
    },
    {
        name: 'animals',
        emojis: [
            { char: '🐐', names: {} },
            { char: '🐪', names: {} },
            { char: '🐫', names: {} },
            { char: '🦙', names: {} },
            { char: '🦒', names: {} },
            { char: '🐘', names: {} },
            { char: '🦣', names: {} },
            { char: '🦏', names: {} },
            { char: '🦛', names: {} },
            { char: '🐭', names: {} },
            { char: '🐁', names: {} },
            { char: '🐀', names: {} },
            { char: '🐹', names: {} },
            { char: '🐰', names: {} },
            { char: '🐇', names: {} },
            { char: '🐿️', names: {} },
            { char: '🦫', names: {} },
            { char: '🦔', names: {} },
            { char: '🦇', names: {} },
            { char: '🐻', names: {} },
            { char: '🐻‍❄️', names: {} },
            { char: '🐨', names: {} },
            { char: '🐼', names: {} },
            { char: '🦘', names: {} },
            { char: '🦡', names: {} },
        ]
    },
    {
        name: 'birds',
        emojis: [
            { char: '🦃', names: {} },
            { char: '🐔', names: {} },
            { char: '🐓', names: {} },
            { char: '🐣', names: {} },
            { char: '🐤', names: {} },
            { char: '🐥', names: {} },
            { char: '🐦', names: {} },
            { char: '🐧', names: {} },
            { char: '🕊️', names: {} },
            { char: '🦅', names: {} },
            { char: '🦆', names: {} },
            { char: '🦢', names: {} },
            { char: '🦉', names: {} },
            { char: '🦤', names: {} },
            { char: '🪶', names: {} },
        ]
    },
    {
        name: 'reptiles',
        emojis: [
            { char: '🐸', names: {} },
            { char: '🐊', names: {} },
            { char: '🐢', names: {} },
            { char: '🦎', names: {} },
            { char: '🐍', names: {} },
            { char: '🐲', names: {} },
            { char: '🐉', names: {} },
        ]
    },
    {
        name: 'marine_animals',
        emojis: [
            { char: '🐳', names: {} },
            { char: '🐋', names: {} },
            { char: '🐬', names: {} },
            { char: '🦭', names: {} },
            { char: '🐟', names: {} },
            { char: '🐠', names: {} },
            { char: '🐡', names: {} },
            { char: '🦈', names: {} },
            { char: '🐙', names: {} },
            { char: '🐚', names: {} },
            { char: '🪸', names: {} },
        ]
    },
    {
        name: 'insects',
        emojis: [
            { char: '🐌', names: {} },
            { char: '🦋', names: {} },
            { char: '🐛', names: {} },
            { char: '🐜', names: {} },
            { char: '🐝', names: {} },
            { char: '🪲', names: {} },
            { char: '🐞', names: {} },
            { char: '🦗', names: {} },
            { char: '🪳', names: {} },
            { char: '🕷️', names: {} },
            { char: '🕸️', names: {} },
            { char: '🦂', names: {} },
            { char: '🦟', names: {} },
            { char: '🦠', names: {} },
        ]
    },
    {
        name: 'plants',
        emojis: [
            { char: '💐', names: {} },
            { char: '🌸', names: {} },
            { char: '💮', names: {} },
            { char: '🏵️', names: {} },
            { char: '🌹', names: {} },
            { char: '🥀', names: {} },
            { char: '🌺', names: {} },
            { char: '🌻', names: {} },
            { char: '🌼', names: {} },
            { char: '🌷', names: {} },
            { char: '🌱', names: {} },
            { char: '🪴', names: {} },
            { char: '🌲', names: {} },
            { char: '🌳', names: {} },
            { char: '🌴', names: {} },
            { char: '🌵', names: {} },
            { char: '🌾', names: {} },
            { char: '🌿', names: {} },
            { char: '☘️', names: {} },
            { char: '🍀', names: {} },
            { char: '🍁', names: {} },
            { char: '🍂', names: {} },
            { char: '🍃', names: {} },
        ]
    },
    {
        name: 'food',
        emojis: [
            { char: '🍇', names: {} },
            { char: '🍈', names: {} },
            { char: '🍉', names: {} },
            { char: '🍊', names: {} },
            { char: '🍋', names: {} },
            { char: '🍌', names: {} },
            { char: '🍍', names: {} },
            { char: '🥭', names: {} },
            { char: '🍎', names: {} },
            { char: '🍏', names: {} },
            { char: '🍐', names: {} },
            { char: '🍑', names: {} },
            { char: '🍒', names: {} },
            { char: '🍓', names: {} },
            { char: '🫐', names: {} },
            { char: '🥝', names: {} },
            { char: '🍅', names: {} },
            { char: '🫒', names: {} },
            { char: '🥥', names: {} },
            { char: '🥑', names: {} },
        ]
    },
    {
        name: 'prepared_food',
        emojis: [
            { char: '🍞', names: {} },
            { char: '🥐', names: {} },
            { char: '🥖', names: {} },
            { char: '🥨', names: {} },
            { char: '🥯', names: {} },
            { char: '🥞', names: {} },
            { char: '🧇', names: {} },
            { char: '🧀', names: {} },
            { char: '🍖', names: {} },
            { char: '🍗', names: {} },
            { char: '🥩', names: {} },
            { char: '🥓', names: {} },
            { char: '🍔', names: {} },
            { char: '🍟', names: {} },
            { char: '🍕', names: {} },
            { char: '🌭', names: {} },
            { char: '🥪', names: {} },
            { char: '🌮', names: {} },
            { char: '🌯', names: {} },
            { char: '🫔', names: {} },
        ]
    },
    {
        name: 'drinks',
        emojis: [
            { char: '🥤', names: {} },
            { char: '🧋', names: {} },
            { char: '🧃', names: {} },
            { char: '🧉', names: {} },
            { char: '🧊', names: {} },
            { char: '🍶', names: {} },
            { char: '🍾', names: {} },
            { char: '🍷', names: {} },
            { char: '🍸', names: {} },
            { char: '🍹', names: {} },
            { char: '🍺', names: {} },
            { char: '🍻', names: {} },
            { char: '🥂', names: {} },
            { char: '🥃', names: {} },
            { char: '☕', names: {} },
            { char: '🫖', names: {} },
            { char: '🍵', names: {} },
        ]
    },
    {
        name: 'travel',
        emojis: [
            { char: '🚗', names: {} },
            { char: '🚕', names: {} },
            { char: '🚙', names: {} },
            { char: '🚌', names: {} },
            { char: '🚎', names: {} },
            { char: '🏎️', names: {} },
            { char: '🚓', names: {} },
            { char: '🚑', names: {} },
            { char: '🚒', names: {} },
            { char: '🚐', names: {} },
            { char: '🚚', names: {} },
            { char: '🚛', names: {} },
            { char: '🚜', names: {} },
            { char: '🏍️', names: {} },
            { char: '🛵', names: {} },
            { char: '🚲', names: {} },
            { char: '🚂', names: {} },
            { char: '🚆', names: {} },
            { char: '🚊', names: {} },
            { char: '🚉', names: {} },
        ]
    },
    {
        name: 'transport',
        emojis: [
            { char: '✈️', names: {} },
            { char: '🛩️', names: {} },
            { char: '🚁', names: {} },
            { char: '🚀', names: {} },
            { char: '🛸', names: {} },
            { char: '⛵', names: {} },
            { char: '🚢', names: {} },
            { char: '🛥️', names: {} },
            { char: '🛳️', names: {} },
            { char: '⚓', names: {} },
        ]
    },
    {
        name: 'time',
        emojis: [
            { char: '⌛', names: {} },
            { char: '⏳', names: {} },
            { char: '⌚', names: {} },
            { char: '⏰', names: {} },
            { char: '⏱️', names: {} },
            { char: '⏲️', names: {} },
            { char: '🕰️', names: {} },
            { char: '🕛', names: {} },
            { char: '🕧', names: {} },
            { char: '🕐', names: {} },
        ]
    },
    {
        name: 'weather',
        emojis: [
            { char: '☀️', names: {} },
            { char: '🌝', names: {} },
            { char: '🌞', names: {} },
            { char: '⭐', names: {} },
            { char: '🌟', names: {} },
            { char: '🌠', names: {} },
            { char: '☁️', names: {} },
            { char: '⛅', names: {} },
        ]
    }
];
